endpoints:
  flight-radar: http://data-live.flightradar24.com/
  flight-radar-api: https://api.flightradar24.com/

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/FLIGHT_CAPACITY
    username: postgres
    password: 899091
  liquibase:
    change-log: classpath:db/changelog.xml

flight-radar:
  api:
    get-flights:
      non-valid-keys: full_count,version